<html>
    <body>
        <div class="small">
        <?= $this->getContent() ?>
<div class="large">
    <div class="col-md-6 col-md-offset-3">
        <div class="page-header">
            <h1>Login to your account</h1>
    <p>We've happy to see you return! Please login to continue</p>
        </div><br>
<div class="large">
    <form action="/MasterUpdate/index/start" role="form" method="post">
        <div class="form-group">
            
            
            <div class="controls">
                <label>Username</label><input type="text" name="username"  placeholder="username" class="first" required>
            </div><br>
        </div>
        <div>
               
            <div>
                <label>Password</label><input type="password" name="password" placeholder="password" class="first" required>
            </div>
        </div>
        <div class="second">
            <input type="checkbox" name="remember" value="1">Remember me on this computer
        </div>
        <div>
                <input type="submit" value="login" class="third">
        </div><br>
        
    </form>
</div>  
       
    </body>

</html>      

