<html>
    <body>
        <div class="col-md-6 col-md-offset-3 six">
            
                     <?= $this->getContent() ?>

                <div class="large">
                    <h2>Login to your account</h2>
                    <p>We've happy to see you return! Please login to continue</p><br>
                
                    <form action="/MasterUpdate/index/start" role="form" method="post">
                        <div>
                            <label>Username</label>
                            <input type="text" name="username" 
                                   value="<?php
                                   if (isset($_COOKIE['username']) != '') {
                                       echo $_COOKIE['username'];
                                   }
                                   ?>" placeholder="username" class="first" required>
                        </div><br>

                        <div>
                            <label>Password</label><input type="password" name="password"
                                                          value="<?php
                                                          if (isset($_COOKIE['password']) != '') {
                                                              echo $_COOKIE['password'];
                                                          }
                                                          ?>" placeholder="password" class="first" required>
                        </div><br>
                        <div class="second">

                            <input type="checkbox" name="remember" value="1">Remember me on this computer
                        </div><br>
                        <div>
                            <a href="/MasterUpdate/forgot/index">Forgot Password?</a>
                            <input type="submit" value="login"  class="third">
                        </div><br>

                    </form>
                    
            </div>
        </div>
    </body>
</html> 



