<?= $this->getContent() ?>
<div class="background">
<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <div class="page-header">
    <h1>Log In</h1>
</div>
<div>
    <form action="/MasterUpdate/index/start" role="form" method="post">
        <div class="form-group">
            <label for="email">Username</label>
            
            <div class="controls">
                <input type="text" id="login_name" name="username" class="form-control" required>
            </div>
        </div>
        <div class="form-group">
                <label for="password">Password</label>
            <div class="controls">
                <input type="password" id="login_name" name="password" class="form-control" required>
            </div>
        </div><br>
        <div class="form-group">
                <input type="submit" value="login" class="btn btn-primary btn-large">
        </div>
        
    </form>
</div>
</div>
       
        
